# Generated by Django 3.2.21 on 2023-10-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20231011_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='url',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True),
        ),
    ]
