# Generated by Django 3.2.21 on 2023-10-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articles_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='url',
        ),
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
