FROM registry.astralinux.ru/astra/ubi18-python311:latest
# Создание пользователя ustor
RUN groupadd -f ustor && useradd -g ustor -m -N ustor || true

# Установка необходимых системных пакетов
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    libpq-dev \
    git \
    python3-venv \
    python3-dev \
    postgresql-server-dev-all \
    ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && update-ca-certificates

# Создание необходимых каталогов
RUN mkdir -p /app /opt/venv /certs /home/ustor/.local /home/ustor/.cache

# Создание venv и установка прав
RUN python3 -m venv /opt/venv && \
    chown -R ustor:ustor /opt/venv /app /certs /home/ustor

WORKDIR /app
ENV PATH="/opt/venv/bin:$PATH"

# Установка системных зависимостей
COPY requirements.txt .
RUN /opt/venv/bin/pip install --no-cache-dir -r requirements.txt && \
    /opt/venv/bin/pip install psycopg2-binary

COPY . .
RUN chown -R ustor:ustor /app /opt/venv

# Установка ustor-utils и ustor-auth
USER ustor
RUN cd /app/ustor-utils && pip install -e . && \
    cd /app/ustor-auth && pip install -e .

USER ustor
RUN ustor-auth generate-all-certs localhost

USER root
RUN cp /app/ustor-auth/ustor_*.{crt,key} /certs/ && \
    chown -R ustor:ustor /certs && \
    chmod 644 /certs/*.crt && \
    chmod 600 /certs/*.key

VOLUME /certs
